// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projeto_API.Data;

namespace Projeto_API.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854");

            modelBuilder.Entity("Projeto_API.Models.Cargo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.ToTable("Cargos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Gerente"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Vendedor"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Entregador"
                        });
                });

            modelBuilder.Entity("Projeto_API.Models.Funcionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CargoId");

                    b.Property<string>("DataNasc");

                    b.Property<string>("Nome");

                    b.Property<string>("Sobrenome");

                    b.HasKey("Id");

                    b.HasIndex("CargoId");

                    b.ToTable("Funcionarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CargoId = 1,
                            DataNasc = "01/01/2000",
                            Nome = "Maria",
                            Sobrenome = "Silva"
                        },
                        new
                        {
                            Id = 2,
                            CargoId = 2,
                            DataNasc = "02/02/2000",
                            Nome = "João",
                            Sobrenome = "Souza"
                        },
                        new
                        {
                            Id = 3,
                            CargoId = 3,
                            DataNasc = "03/03/2000",
                            Nome = "José",
                            Sobrenome = "Oliveira"
                        });
                });

            modelBuilder.Entity("Projeto_API.Models.Funcionario", b =>
                {
                    b.HasOne("Projeto_API.Models.Cargo", "Cargo")
                        .WithMany("Funcionarios")
                        .HasForeignKey("CargoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
